# .github/workflows/e2e.yml
name: Test — Cypress [E2E]

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "melodex-front-end/**"
      - "melodex-back-end/**"
      - "tests/cypress/**"
      - "cypress.config.*"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/**"
  push:
    branches: [main]
    paths:
      - "melodex-front-end/**"
      - "melodex-back-end/**"
      - "tests/cypress/**"
      - "cypress.config.*"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      spec:
        description: "Spec glob (default: all e2e)"
        required: true
        default: "tests/cypress/e2e/**/*.cy.{ts,tsx,js,jsx}"
      browser:
        description: "Browser"
        required: true
        default: "chrome"

permissions:
  contents: read

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    # Run automatically only when the flag is on; always allow manual dispatch
    if: ${{ github.event_name == 'workflow_dispatch' || vars.E2E_LIVE_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      NODE_ENV: test
      # You can set baseUrl via env or via `with.config` below. Using both is fine.
      CYPRESS_baseUrl: http://localhost:3001
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # ⬇️ Start your web app. Make sure this command serves on port 3001.
      # If your dev script serves a different port, change it or use a preview/build script that serves 3001.
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: npm run dev
          wait-on: "http://localhost:3001"
          wait-on-timeout: 120
          browser: ${{ github.event_name == 'workflow_dispatch' && inputs.browser || 'chrome' }}
          spec: ${{ github.event_name == 'workflow_dispatch' && inputs.spec || 'tests/cypress/e2e/**/*.cy.{ts,tsx,js,jsx}' }}
          # If you prefer passing baseUrl here instead of env, uncomment:
          # config: baseUrl=http://localhost:3001

      - name: Upload Cypress artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-e2e-artifacts
          path: |
            tests/cypress/screenshots
            tests/cypress/videos
          if-no-files-found: ignore
