name: Test (Vitest + Cypress)

on:
  push:
    branches: [ "main" ]
    paths:
      - "tests/**"
      - "src/**"
      - "backend/**"
      - "vitest.config.*"
      - "cypress.config.*"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "tests/**"
      - "src/**"
      - "backend/**"
      - "vitest.config.*"
      - "cypress.config.*"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/test.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vitest:
    name: Vitest (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ "unit-ui", "integration" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run Vitest (${{ matrix.project }})
        run: npx vitest run --project ${{ matrix.project }}

  cypress:
    name: Cypress (E2E skeletons)
    runs-on: ubuntu-latest
    needs: vitest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # We don't start the app here—your placeholder specs are baseUrl-gated
      # If/when you add real visits, set CYPRESS_BASE_URL and start the server.

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          # Point Cypress at your repo root config and specs under tests/cypress/e2e
          spec: tests/cypress/e2e/**/*.cy.{ts,tsx}
          # No 'start' command because placeholders don't need the app running
          browser: chrome
          install: false

      - name: Upload Cypress artifacts (on fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            tests/cypress/screenshots
            tests/cypress/videos
          if-no-files-found: ignore
